language: fr

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 300
policies:
  - name: "policy.RestaurantPolicy"
    batch_size: 64
    epochs: 100
    validation_split: 0.2
  - name: MemoizationPolicy
  - name: MappingPolicy