language: fr

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 50

policies:
  - name: "policy.RestaurantPolicy"
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: MappingPolicy